pipeline {
    agent any

    environment {
        DOCKER_REPO = 'pranav5/end-to-end-devops-project'
        CLUSTER     = 'devops-project'
        REGION      = 'us-east-1'
    }

    stages {

        stage('Checkout') {
            steps {
                echo ' Cloning repository...'
                checkout scm
            }
        }

        stage('Build Backend Image') {
            steps {
                echo ' Building backend image...'
                sh 'docker build -t $DOCKER_REPO:backend-latest ./kubernetes/apps/backend'
            }
        }

        stage('Build Frontend Image') {
            steps {
                echo ' Building frontend image...'
                sh 'docker build -t $DOCKER_REPO:frontend-latest ./kubernetes/apps/frontend'
            }
        }

        stage('Push to DockerHub') {
            steps {
                echo ' Pushing images to DockerHub...'
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $DOCKER_REPO:backend-latest
                        docker push $DOCKER_REPO:frontend-latest
                    '''
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                echo ' Deploying to EKS...'
                sh '''
                    aws eks update-kubeconfig --name $CLUSTER --region $REGION
                    kubectl rollout restart deployment/backend -n app
                    kubectl rollout restart deployment/frontend -n app
                    kubectl rollout status deployment/backend -n app --timeout=120s
                    kubectl rollout status deployment/frontend -n app --timeout=120s
                '''
            }
        }

        stage('Verify') {
            steps {
                echo ' Verifying deployment...'
                sh '''
                    kubectl get pods -n app
                    kubectl get service frontend-service -n app
                '''
            }
        }
    }

    post {
        success {
            echo ' Pipeline completed! App is live.'
        }
        failure {
            echo ' Pipeline failed. Check logs above.'
        }
        always {
            echo ' Cleaning up local Docker images...'
            sh '''
                docker rmi $DOCKER_REPO:backend-latest  || true
                docker rmi $DOCKER_REPO:frontend-latest || true
                docker logout || true
            '''
        }
    }
}
